### ISSUE TITLE
标签可以设置ImageView吗?

### ISSUE THREAD

**Issue by xoptimal** [oubowu/PinnedSectionItemDecoration#1]
在几个粘性库中,  都没有解决这个问题 ~

**Comment by oubowu** [comment]
如果你图片是本地加载的就okay，如果是网络加载会异常，这个问题我看下

**Comment by xoptimal** [comment]
相信你也了解, 大部分的图片都是异步  ~

现在大部分粘性库, 第一次加载数据后 , 图片都不显示 (现在做法是模拟滑动或者把图片缓存起来再加载,)

我只能说, 好麻烦 0.0

**Comment by oubowu** [comment]
搞定了，最新代码可以在你的iamgeview宽高固定的情况，显示正常

**Comment by oubowu** [comment]
不行的情况是我忘了手动测量标签的宽度，现在应该是没啥问题了，用glide的话，wrap＿content的话图片未加载出来的时候是它设置的默认宽高会很小，要等到图片加载出来才是正确的宽高，所以你使用的话给定宽高，应该没啥问题了，因为这个标签是我手动调用adpter.createholder
和bindholder的，它也是会去调用glide加载图片的
