### ISSUE TITLE
ambiguous method call.both

### ISSUE THREAD

**Issue by liuyuttkx** [oubowu/PinnedSectionItemDecoration#11]
在使用BaseRecyclerviewAdapterHelper 2.4.4版本及以上时,重写onViewAttachedToWindow会报错
ambiguous method call.both

楼主可以试一下,最新BaseRecyclerviewadapterhelper. 
使用楼主导入的BaseRecyclerviewadapterhelper版本没有问题

**Comment by oubowu** [comment]
改到2.4.4了，只是泛型多了个K extend BaseViewHolder，调整了下发现没有问题啊，你能把你的代码贴下么？我的adapter都会重写onViewAttachedToWindow的，没有报错 @liuyuttkx

**Comment by oubowu** [comment]
代码更新到v2.6.1了，你拉下再试试？ @liuyuttkx

**Comment by liuyuttkx** [comment]
您好,最终测试发现是我用的studio软件误报. 报错后仍然编译正常运行. (第一次发现会出现这样)但"holder"代码那块一直会报红.
我用的都是线性布局,索性我也不用重写那两个方法. 事情完成解决.
十分感谢楼主!!!!
报错代码如下,报错点在"holder"这里.  
 @Override
    public void onViewAttachedToWindow(BaseViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        FullSpanUtil.onViewAttachedToWindow(holder, this, StockEntity.StockInfo.TYPE_HEADER);
    }

**Comment by oubowu** [comment]
FullSpanUtil.onViewAttachedToWindow(holder, this, StockEntity.StockInfo.TYPE_HEADER)
如果是瀑布流布局，这里处理标签的布局占满一行

原因我可能知道了，它的父方法调用了这个
`    public void onViewAttachedToWindow(K holder) {
        super.onViewAttachedToWindow(holder);
        int type = holder.getItemViewType();
        if(type != 1365 && type != 273 && type != 819 && type != 546) {
            this.addAnimation(holder);
        } else {
            this.setFullSpan(holder);
        }

    }

    protected void setFullSpan(ViewHolder holder) {
        if(holder.itemView.getLayoutParams() instanceof LayoutParams) {
            LayoutParams params = (LayoutParams)holder.itemView.getLayoutParams();
            params.setFullSpan(true);
        }

    }`

然后我再重写的时候super.onViewAttachedToWindow(holder); 所以方法调用两次了，居然会报错~~~

所以你去掉也没问题，但是你不能保证其他框架适配器有做这个吧，所以你看个人情况加咯

**Comment by liuyuttkx** [comment]
十分感谢!!!
您说的这个问题 ,可以在BaseQuickAdapter中做修改, onViewAttachedToWindow方法中暴露一个接口出来,需要的话就实现该接口.您看如何. 这样也不会引起报红


liuyu195@126.com
 
From: Ou Bowu
Date: 2016-11-24 20:17
To: oubowu/PinnedSectionItemDecoration
CC: liuyuttkx; Mention
Subject: Re: [oubowu/PinnedSectionItemDecoration] ambiguous method call.both (#11)
FullSpanUtil.onViewAttachedToWindow(holder, this, StockEntity.StockInfo.TYPE_HEADER)
如果是瀑布流布局，这里处理标签的布局占满一行
原因我可能知道了，它的父方法调用了这个
` public void onViewAttachedToWindow(K holder) {
super.onViewAttachedToWindow(holder);
int type = holder.getItemViewType();
if(type != 1365 && type != 273 && type != 819 && type != 546) {
this.addAnimation(holder);
} else {
this.setFullSpan(holder);
}
}
protected void setFullSpan(ViewHolder holder) {
    if(holder.itemView.getLayoutParams() instanceof LayoutParams) {
        LayoutParams params = (LayoutParams)holder.itemView.getLayoutParams();
        params.setFullSpan(true);
    }
}`

然后我再重写的时候super.onViewAttachedToWindow(holder); 所以方法调用两次了，居然会报错~
所以你去掉也没问题，但是你不能保证其他框架适配器有做这个吧，所以你看个人情况加咯

**Comment by oubowu** [comment]
BaseQuickAdapter不是我写的 其实这里用这个适配器只是方便演示 只要实现任意适配器就行 根据实际情况处理即可
