### ISSUE TITLE
为何仓库找不到这个依赖包?

### ISSUE THREAD

**Issue by greatflag** [oubowu/PinnedSectionItemDecoration#12]
加了jcenter()  https://jitpack.io 找不到这个包,  改成'com.github.oubowu:PinnedSectionItemDecoration:-SNAPSHOT' 能下载到

**Comment by greatflag** [comment]
jcenter()要改成 
jcenter {
            url "http://jcenter.bintray.com/"
        }
.....................

**Comment by oubowu** [comment]
我用的是com.novoda.bintray-release这个插件上传到bintray的

**Comment by oubowu** [comment]
刚刚找了个项目compile了下 木有问题哦
