### ISSUE TITLE
头部子控件点击事件无效

### ISSUE THREAD

**Issue by funfang** [oubowu/PinnedSectionItemDecoration#13]
RT，头部子控件的点击事件无法扑捉，只有点击整个头部的事件，无法定位到具体的。而且DEMO本身也是无法正常点击头部子控件的。像那个more的点击事件。

**Comment by funfang** [comment]
DEMO里股票那个可以扑捉到More的点击事件，可是我自己的无法实现，每次显示被点击的ID都为-1，我看源码里默认没设置view的ID和clicklisener导致的，可是这些我都设置了，还是无法扑捉，与BaseRecyclerViewAdapterHelper配合使用的。

**Comment by funfang** [comment]
这是我的代码
`itemDecoration = new PinnedHeaderItemDecoration.Builder(BaseHeaderAdapter.TYPE_HEADER)
                .setClickIds(R.id.tv_item_camp_img_selectall_cancel, R.id.tv_item_camp_imgs_date_city).disableHeaderClick(false)
                .setHeaderClickListener(headerClickAdapter).create();

        rvCampImg.addItemDecoration(itemDecoration);`

**Comment by funfang** [comment]
这是我的代码：
`itemDecoration = new PinnedHeaderItemDecoration.Builder(BaseHeaderAdapter.TYPE_HEADER)         .setClickIds(R.id.tv_item_camp_img_selectall_cancel,R.id.tv_item_camp_imgs_date_city).disableHeaderClick(false).setHeaderClickListener(headerClickAdapter).create();
rvCampImg.addItemDecoration(itemDecoration);`

**Comment by oubowu** [comment]
能弄个demo过来我看下吗，另外我新写了个库https://github.com/oubowu/StickyItemDecoration 你可以尝试下这个

**Comment by funfang** [comment]
好的，我先看看你新的库，不行我再弄个DEMO，谢谢。

**Comment by funfang** [comment]
我已经试了你新的库了，发现一个问题，当我不滚动的时候，第一个section的头部点击无法获取，滚动一点就可以获取到了，滚回到最上面的时候就又无法点击了。我猜是最上面悬浮层虽然看不到，但拦截了点击事件，无法点击穿透。

**Comment by oubowu** [comment]
那个demo没有设置适配器的点击事件 你可以设置下适配器item点击事件再看看

**Comment by oubowu** [comment]
StickyItemDecoration代码已更新，测了头部点击和Item点击没有冲突

**Comment by funfang** [comment]
不是的，真的有问题，你的代码里有屏蔽，我注释掉就可以了。你的代码如下：
`public StickyHeadContainer(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
//        setOnClickListener(new OnClickListener() {
//            @Override
//            public void onClick(View v) {
//                // TODO: 2017/1/9 屏蔽点击事件
//            }
//        });
    }`

**Comment by oubowu** [comment]
这个肯定要屏蔽掉的 因为如果你不屏蔽的话 你后面遮住的item设置了点击事件 你去点击粘性头部的时候就会响应后面的item了

**Comment by funfang** [comment]
我把你这个屏蔽部分注释掉后没有影响到后面item的点击，即使头部和后面Item重叠在一点也不会影响后面的点击。

**Comment by oubowu** [comment]
我用过直播吧这个APP就是我点击他的粘性头部 他结果响应了后面的item跳转了 个人感觉不太合理 你觉得呢

**Comment by funfang** [comment]
它响应了后面的item跳转其实就是点击穿透问题，直接在头部的点击事件里返回true就可以防止穿透了，不向下传递。

**Comment by oubowu** [comment]
设置点击事件也能防止穿透而且更加方便

**Comment by funfang** [comment]
嗯
