### ISSUE TITLE
如何设置header背景透明

### ISSUE THREAD

**Issue by AndyGu** [oubowu/PinnedSectionItemDecoration#14]
如题

**Comment by oubowu** [comment]
它的原理就是根据位置手动生成头部view绘制在recyclerview上面，其实并没有真正添加到recyclerview上面，你想透明前提是你原来的header的item布局背景颜色就是透明的

**Comment by antoantonyk** [comment]
@oubowu  could you please write in english? I need to make the background of the view transparent. I tried to make the background transparent  color, but its not working.
