### ISSUE TITLE
两个小 bug ～

### ISSUE THREAD

**Issue by ebnbin** [oubowu/PinnedSectionItemDecoration#17]
滚动到顶部，RecyclerView 的 edge ripple 效果会被 pinned header 覆盖，给的 demo 中 BigPinnedHeader 中也存在这个问题，StockActivity 没有这个问题，因为往 adapter 中添加了一个 headerView，就不存在这个问题了。？？

如果 PinnedHeaderItemDecoration 不添加 divider，存在一像素（或 1dp？）的边缘情况，会导致 pinned header 显示的是上一个 header 的内容。

**Comment by oubowu** [comment]
1.这个的原理是取出对应头部item，创建一个view然后绘制在recyclerview上面，可能是绘制的导致一些效果没了
2.它是取当前头部加0.1像素下面的view做判断，可能不准
然后我建议你可以尝试下https://github.com/oubowu/StickyItemDecoration这个项目，感觉会好点
