### ISSUE TITLE
通过头部数据，定位到相应的头部

### ISSUE THREAD

**Issue by Troll4it** [oubowu/PinnedSectionItemDecoration#21]
我看下了源码中的方法，没有找到快速通过头部的数据定位到相应头部的方法，请问有吗？、谢谢

**Comment by oubowu** [comment]
有个私有变量 mPinnedHeaderPosition  可以定位的

**Comment by Troll4it** [comment]
mHeaderItemDecoration.getPinnedHeaderPosition()通过此方法拿到了都是-1，望明示，谢谢

**Comment by oubowu** [comment]
是不是还没有生成粘性头部 没有生成的时候 就是-1的

**Comment by Troll4it** [comment]
生成了，在recycleView滑动的过程中，看到了粘性头部，这是我主要代码


        rv.setLayoutManager(new LinearLayoutManager(StickyItemActivity.this, LinearLayoutManager.VERTICAL, false));
        StickyAdapter adapter = new StickyAdapter(initData());
        rv.setAdapter(adapter);
        mHeaderItemDecoration = new PinnedHeaderItemDecoration.Builder(StickyDataBean.StickyInfo.TYPE_HEADER).create();
        rv.addItemDecoration(mHeaderItemDecoration);
        mHeaderItemDecoration.setDataPositionOffset(adapter.getHeaderLayoutCount());
        int pinnedHeaderPosition = mHeaderItemDecoration.getPinnedHeaderPosition();
        Log.i(TAG, "initView: " + pinnedHeaderPosition);

**Comment by oubowu** [comment]
你初始化完立刻就调这个方法？尝试着加个滑动监听，在里面打印出来看下

**Comment by Troll4it** [comment]
刚测试了，初始化立刻调用拿到的事-1，但是加个滑动监听，就能拿到相应的位置，利用这个就能自己撸一个通讯录出来了。。谢谢您的耐心的指导
