### ISSUE TITLE
如何实现图中的这种线呢？

### ISSUE THREAD

**Issue by zjc** [oubowu/PinnedSectionItemDecoration#23]
![image](https://user-images.githubusercontent.com/1041554/27680604-e5287142-5cee-11e7-84db-460526c54719.png)

**Comment by oubowu** [comment]
itemdecoration可以实现

**Comment by zjc** [comment]
我实现了这个线，但是距离有点问题，一直不知道该怎么调节，能帮我处理一下么？万分感谢 QQ：644952013
