### ISSUE TITLE
如果有2个header，需要执行不一样的操作，请问该怎么处理呢。

### ISSUE THREAD

**Issue by Anayuta** [oubowu/PinnedSectionItemDecoration#27]

**Comment by oubowu** [comment]
你指的两个不同header是两个不同类型的header，还是同一个类型但是数据不同的header？这个库只支持同一个类型的header

**Comment by Anayuta** [comment]
比如你的demo中  一个header是涨幅榜，一个是跌幅榜。我点击涨幅榜的需要弹出111，点击跌幅榜弹出222。这样的话能实现么？

**Comment by Anayuta** [comment]
@oubowu  同一个类型数据不同的header，但是header想执行不一样的操作，有没好的思路分享下。

**Comment by oubowu** [comment]
有 getPinnedHeaderPosition这个方法，你拿到它的位置自然知道是对应的哪个榜了，就可以做处理啦

**Comment by Anayuta** [comment]
@oubowu   好的，我待会试试。谢谢你的分享
