### ISSUE TITLE
请问是否支持粘性标签滑动监听，还有指定滑动某个标签到头部？

### ISSUE THREAD

**Issue by wfs3006** [oubowu/PinnedSectionItemDecoration#28]
非常棒的一个库，开发中遇到一个问题，项目中让做的效果图如下：

左侧菜单点击可以快速定位该分类到顶部，右侧分类滑出该分类则左侧菜单切换到相应分类，想问下，该库中是否支持滑动监听，或者有什么思路，望提供，谢谢！

**Comment by oubowu** [comment]
可以根据你点击的菜单种类 调recyclerview.smothscrolltoposition 这个位置应该你是能算出来的 无非就是此种类列表的首位置-1 就对应粘性头部
