### ISSUE TITLE
请问能结合RecyclerViewAdapterHelper库的SecionAdapter来实现吗?

### ISSUE THREAD

**Issue by zofnk** [oubowu/PinnedSectionItemDecoration#29]
我看了你的demo 是以BaseMultiItemQuickAdapter多布局Adapter的...如果以Section来的话是怎样添加进去?

**Comment by oubowu** [comment]
这个我有空研究一下

**Comment by oubowu** [comment]
`public class SectionAdapter extends BaseSectionQuickAdapter<MySection, BaseViewHolder> {
   // 将头部布局类型暴露出来
    public static final int SECTION_HEADER_VIEW = BaseSectionQuickAdapter.SECTION_HEADER_VIEW;`
照常使用即可，就这么简单@zofnk
`mRecyclerView.addItemDecoration(new PinnedHeaderItemDecoration.Builder(SectionAdapter.SECTION_HEADER_VIEW).setDividerId(R.drawable.divider).enableDivider(true)
                .setHeaderClickListener(null).create());`
