### ISSUE TITLE
问一下这个两种数据在集合里面是同级别的嘛

### ISSUE THREAD

**Issue by alguojian** [oubowu/PinnedSectionItemDecoration#30]
我是要做图书卷和章列表，数据是最外层list集合包含所有的卷，每一卷又是一个集合（包含该卷所有章节），这种可以用该库做嘛，有时间请回复我一下，谢谢。

**Comment by oubowu** [comment]
你头部是想以章节为头部吗？是的话没问题

**Comment by alguojian** [comment]
就是想卷是头部，章是列表，卷滑动最上面可以悬停的效果（感觉表达不清楚了~~）

**Comment by oubowu** [comment]
应该没问题 那你卷的那个作为粘性头部就行了吧
