### ISSUE TITLE
配合加载更多使用问题

### ISSUE THREAD

**Issue by CLOUD-wuzichen** [oubowu/PinnedSectionItemDecoration#32]
配合加载更多使用时候，底部的loadingView没有显示，应该是在10条数据之下，会不会是加多个sticky布局高度算进去了 我的sticky高度刚好为45dp与BaseRecyclerViewAdapterHelper加载更多View一样，请问下是框架支持问题还是我使用错了？谢谢

**Comment by oubowu** [comment]
我看下

**Comment by oubowu** [comment]
刚刚测了 没有影响 底部lodingview跟那个头部没有联系的 头部只是根据你recyclerview里面的头部布局绘制出来的 ， 你是不是在回调里面测试添加数据的时候没有延时，导致它一瞬间加载完了，所以你没看到底部loading的效果
`        sectionAdapter.setLoadMoreView(new CustomLoadMoreView());
        sectionAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {

            int c = 5;

            @Override
            public void onLoadMoreRequested() {
                List<MySection> list = sectionAdapter.getData();
                list.add(new MySection(true, "Section "+(c++), false));
                list.add(new MySection(new Video(HTTPS_AVATARS1_GITHUBUSERCONTENT_COM_LINK, CYM_CHAD)));
                list.add(new MySection(new Video(HTTPS_AVATARS1_GITHUBUSERCONTENT_COM_LINK, CYM_CHAD)));
                mRecyclerView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        sectionAdapter.loadMoreComplete();
                    }
                }, 2000);
            }
        },mRecyclerView);`

**Comment by CLOUD-wuzichen** [comment]
好的谢谢 我再复述下场景，在fragment中使用，UI布局为广告banner+filter筛选+列表数据，其中filter为粘性效果，配合BaseRecyclerViewAdapterHelper加载更多使用。
问题1：ui问题如上个问题
问题2：粘性的bean只是作为type使用，应不作加载更多的判断使用，所以判断一页是否大于10条时应去除粘性bean
问题3：如果stickyView是自定义view的viewgroup，如何抓去stickyView中子view的事件（或者是有没办法get出子View但不要响应原有的onclick事件，自己单独写个事件）
ps：回答过就忽略，麻烦给下建议

**Comment by oubowu** [comment]
问题1，你可以在加载更多那里，延时调用loadMoreComplete看下是否有效果
问题2，这样判断没问题
问题3，绘制的头部我是有处理点击事件的，只要你自定义的viewgroup给你的子view设置id，在初始化itemdecoration的时候 setClickIds(R.id.iv_more，R.id.xxx，。。。)，类似下面处理即可
`OnHeaderClickAdapter clickAdapter = new OnHeaderClickAdapter() {

          @Override
          public void onHeaderClick(View view, int id, int position) {
              switch (id) {
                  case R.id.fl:
                       // case OnItemTouchListener.HEADER_ID:
                       Toast.makeText(StockActivity.this, "click, tag: " + mAdapter.getData().get(position).pinnedHeaderName, Toast.LENGTH_SHORT).show();
                       break;
                   case R.id.iv_more:
                       Toast.makeText(StockActivity.this, "click " + mAdapter.getData().get(position).pinnedHeaderName + "'s more button", Toast.LENGTH_SHORT)
                             .show();
                       break;
                   case R.id.checkbox:
                       final CheckBox checkBox = (CheckBox) view;
                       checkBox.setChecked(!checkBox.isChecked());
                       // invalidate ItemDecorations to draw the header
                       mRecyclerView.invalidateItemDecorations();

                       mAdapter.getData().get(position).check = checkBox.isChecked();
                       mAdapter.notifyItemChanged(position + mHeaderItemDecoration.getDataPositionOffset());

                       break;
               }
           }

       };

     mRecyclerView.addItemDecoration(
             new PinnedHeaderItemDecoration.Builder(StockEntity.StockInfo.TYPE_HEADER)
             .setClickIds(R.id.iv_more)
             .setHeaderClickListener(clickAdapter)
             .create());`

**Comment by CLOUD-wuzichen** [comment]
我的sticky是filter而且是动态添加的，类似于商品排序按价格高低、销量高低这样，举例代码如下
   private void addTab(final int position, List<String> tabList, View tabView) {
        final RelativeLayout rlContent = (RelativeLayout) tabView.findViewById(R.id.rl_content);
        TextView tvTitle = (TextView) tabView.findViewById(R.id.tv_title);
        View line = tabView.findViewById(R.id.rl_line);
        if (position == 0) {
            line.setVisibility(GONE);
        }
        if (tabList.get(position) != null) {
            tvTitle.setText(tabList.get(position));
        }
        rlContent.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (position == mCurrentPosition) {
                    if (tabStatusList.get(position) == DOWN) {
                        tabStatusList.set(position, UP);
                    } else {
                        tabStatusList.set(position, DOWN);
                    }
                    setArrowBackground(position, tabStatusList.get(position));
                } else {
                    mCurrentPosition = position;
                    tabStatusList.set(mCurrentPosition, DOWN);
                    setArrowBackground(mCurrentPosition, DOWN);
                }
                if (null != onTabClickListener)
                    onTabClickListener.tabClick(mCurrentPosition, tabStatusList.get(mCurrentPosition));
            }
        });
        LayoutParams lp = new LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.MATCH_PARENT);
        lp.weight = 1;
        rootView.addView(tabView, position, lp);
    }

然后对外暴露选择的位置和箭头方向
 public interface TabClickListener {
        void tabClick(int position, int status);
    }

所以就不是楼主那种单纯的点击事件，其实我目的就想响应自己的事件来切换箭头状态，麻烦看下有没思路

**Comment by oubowu** [comment]
绘制头部这种做法可以做简单的展示效果的，对于需要对头部做一些效果的话你看下我这个https://github.com/oubowu/StickyItemDecoration 能不能契合你的使用场景，这个的做法是在recyclerview顶部放置一个布局，然后根据监听位移来处理，这个布局是真实存在的，所以可以切换箭头状态

**Comment by CLOUD-wuzichen** [comment]
正好我也试了 我也反映下问题，补充说明：列表数据和头部广告的接口是分开的，谁先响应看服务器返回，所以这样做法会导致2次刷新列表
遇到问题1.进入页面时顶部的外置布局就出现，导致页面有2个filter，框架源码暂时还没仔细看是通过什么判断显示外置布局的，麻烦说明下我该注意什么地方

**Comment by oubowu** [comment]
你能精简一个demo的话 我帮你分析吧 这样子我也不知道具体情况 
这里做的，把外面那个布局传进来后，根据当前recyclerview第一个可见的位置，大于的话就显示头部，小于或者等于-1时，隐藏头部
`    @Override
    public void onDraw(Canvas c, RecyclerView parent, RecyclerView.State state) {
        super.onDraw(c, parent, state);

        checkCache(parent);

        if (mAdapter == null) {
            // checkCache的话RecyclerView未设置之前mAdapter为空
            return;
        }

        calculateStickyHeadPosition(parent);

        if (mEnableStickyHead /*&& mFirstCompletelyVisiblePosition > mStickyHeadPosition*/ && mFirstVisiblePosition >= mStickyHeadPosition && mStickyHeadPosition != -1) {
            View belowView = parent.findChildViewUnder(c.getWidth() / 2, mStickyHeadContainer.getChildHeight() + 0.01f);
            mStickyHeadContainer.onDataChange(mStickyHeadPosition);
            int offset;
            if (isStickyHead(parent, belowView) && belowView.getTop() > 0) {
                offset = belowView.getTop() - mStickyHeadContainer.getChildHeight();
            } else {
                offset = 0;
            }
            mStickyHeadContainer.scrollChild(offset);
            mStickyHeadContainer.setVisibility(View.VISIBLE);
        } else {
            mStickyHeadContainer.reset();
            mStickyHeadContainer.setVisibility(View.INVISIBLE);
        }

    }`

**Comment by CLOUD-wuzichen** [comment]
谢谢耐心指导 我先试着解决下先
