### ISSUE TITLE
请问初始化悬浮标题的时候可以获取到悬浮标题的子控件吗

### ISSUE THREAD

**Issue by yxlku** [oubowu/PinnedSectionItemDecoration#34]
大神，请问初始化悬浮标题的时候可以获取到悬浮标题的子控件吗？然后给子控件设置一些属性

**Comment by oubowu** [comment]
由于这个标题是绘制出来的，所以拿不到的，我建议你试下我另外实现的这个https://github.com/oubowu/StickyItemDecoration

**Comment by yxlku** [comment]
好的，谢谢大神 的回复
