### ISSUE TITLE
[问题]这样删除增加一些数据吸顶的数据能更新吗

### ISSUE THREAD

**Issue by nicelyjust** [oubowu/PinnedSectionItemDecoration#37]
这样删除增加一些数据吸顶的数据能更新吗

**Comment by oubowu** [comment]
调用RecyclerView.invalidateItemDecorations()可以重新绘刷新头部

**Comment by nicelyjust** [comment]
@oubowu 谢谢解答,再请教个问题: 现在貌似不支持gridlayoutmanager spancount吧,可以考虑增加这个功能吗[赞]

**Comment by oubowu** [comment]
`  @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        FullSpanUtil.onAttachedToRecyclerView(recyclerView, this, StockEntity.StockInfo.TYPE_HEADER);
    }

    @Override
    public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        FullSpanUtil.onViewAttachedToWindow(holder, this, StockEntity.StockInfo.TYPE_HEADER);
    }`
网格和瀑布流的处理是粘性头部默认占满一行，你想粘性头部只占一部分？这样子显然不合逻辑

**Comment by nicelyjust** [comment]
@oubowu 嗯嗯,谢谢耐心解惑
