### ISSUE TITLE
使用上下回弹的RV时,粘性头部会盖住界面顶部UI

### ISSUE THREAD

**Issue by nicelyjust** [oubowu/PinnedSectionItemDecoration#38]
如题, 知道是绘制在界面之上导致的,但没有解决的思路

**Comment by oubowu** [comment]
你能够监听到rv的顶部y坐标吗 然后在回弹时根据y坐标被动禁止粘性头部 试一下

**Comment by nicelyjust** [comment]
@oubowu 禁止粘性头部,貌似没这个方法吧

**Comment by oubowu** [comment]
/**
     * 禁止绘制粘性头部
     *
     * @param disableDrawHeader true的话不绘制头部，默认false绘制头部
     */
    public void disableDrawHeader(boolean disableDrawHeader) {
        mDisableDrawHeader = disableDrawHeader;
        if (mParent != null) {
            mParent.invalidateItemDecorations();
        }
    }

**Comment by iielse** [comment]
@nicelyjust  https://github.com/oubowu/PinnedSectionItemDecoration/issues/49 这种效果吗？

https://github.com/Mixiaoxiao/OverScroll-Everywhere
