### ISSUE TITLE
旋转屏幕时,第一个粘性头部不绘制(宽度占不了整屏宽度)

### ISSUE THREAD

**Issue by nicelyjust** [oubowu/PinnedSectionItemDecoration#39]
旋转屏幕时,第一个粘性头部不绘制(宽度占不了整屏宽度),滑动至第二个分类位置时,第一个才恢复正常.

**Comment by oubowu** [comment]
你尝试下 在旋转屏幕的生命周期调下 recyclerview.invaliateitemdecorations 试下看能不能正确绘制出来

**Comment by nicelyjust** [comment]
@oubowu  调这个API没有效果, 通过这样的方式解决的 
  mRv.setAdapter(null);
  mRv.setAdapter(mAdapter);   [smile]
