### ISSUE TITLE
粘性头部可以设置划走吗

### ISSUE THREAD

**Issue by messishow** [oubowu/PinnedSectionItemDecoration#4]
粘性头部可以设置的像其它item一样上滑消失吗，有没有一个参数可以让粘性头部可以粘住也可以划走？，还有这个粘性头部支持复杂的布局吗，像播放视频

**Comment by oubowu** [comment]
之前没有想到这个需求，但是我可以实现它，你需要的话我就写吧，到时通知你。支持复杂的布局你指的是多种不同type的类型布局吗？按原理是完全没问题的！

**Comment by messishow** [comment]
回复好及时，赞一个，有这个需要，我也看看你的源码吧，学习一下你实现的原理。我说的复杂布局就是在这个粘性头部里面播放视频，不是多个type的类型布局，由于今天刚看到你的项目，没仔细看你的源码，所以就咨询了一下。

**Comment by oubowu** [comment]
应该是没问题的，我得去实验下，刚好最近在弄那个Ijkplayer

**Comment by oubowu** [comment]
有没有一个参数可以让粘性头部可以粘住也可以划走：这个是划走是指那种侧滑么？

**Comment by messishow** [comment]
你是策划，就是上下滑动

**Comment by messishow** [comment]
不是侧滑，就是上下滑动

**Comment by messishow** [comment]
我试了，好像不能把粘性头部做成像普通item一样滑动消失，就是像item一样向上滑动的时候消失

**Comment by oubowu** [comment]
你是想动态设置它固定或者不固定的意思吗？就是可以通过代码设置当前粘性头部是不是固定的意思？

**Comment by oubowu** [comment]
你看看我新建的分支fix-header，是要这种效果吗？

**Comment by Cenler** [comment]
Adpater.addHeaderView() 之后滑动异常

**Comment by oubowu** [comment]
可以具体点吗？@Cenler

**Comment by Cenler** [comment]
BaseQuickAdapter 添加一个头部, 会导致滑动头部滑动偏移异常, 具体效果貌似是忽略了头部Item的高度, 你可以添加一个头部试试 @oubowu

**Comment by oubowu** [comment]
好 我试下 待会给你答复

**Comment by oubowu** [comment]
好 我试下 待会给你答复@Cenler

**Comment by oubowu** [comment]
已经修复，请更新代码，多谢

**Comment by oubowu** [comment]
已经修复，请更新代码，多谢@Cenler

**Comment by oubowu** [comment]
更新最新依赖即可，多谢提bug@Cenler

**Comment by oubowu** [comment]
更新最新依赖即可，多谢提bug @Cenler

**Comment by Cenler** [comment]
使用BaseQuickAdapter2.+后的版本试了下, 两个库的事件处理机制有交集, 导致PinnedHeader与被覆盖的Item都触发了事件回调.  另外还有头部的点击事件, 滑动隐藏后再展示事件的点击判断区域(ClickBounds)与PinnedHeader不匹配, 还有个情况就是PinnedHeader固定顶部时如果存在CheckBox or RadioButton等控件时状态会丢失, 准备拿源码进行定制!!

**Comment by oubowu** [comment]
原因就是BaseQuickAdapter2.+后它也是用ItemTouchHelper来做点击的判断，这个跟我的冲突了 @Cenler 
其他问题我再看看

**Comment by oubowu** [comment]
事件处理机制有交集解决方法，我那边通过反射拿到mOnItemTouchListeners，然后把我的mItemTouchListener添加到索引0位置；之前交集的问题是由于他addOnItemTouchListener比我那里快，所以他没有拦截还传给我；而我的话处理完头部的话就把事件全部消费掉了。更新依赖即可，其他两个再看@Cenler

**Comment by oubowu** [comment]
全部解决 @Cenler
