### ISSUE TITLE
点击事件不能识别子View的id

### ISSUE THREAD

**Issue by drrino** [oubowu/PinnedSectionItemDecoration#42]
![6ix415g 5zv0 b9hk e 7](https://user-images.githubusercontent.com/14050360/36519268-6fe7d822-17c5-11e8-9e76-f2190b1b1eaf.png)

当我释放switch的注释 不能调用dialog

**Comment by oubowu** [comment]
你是点击粘性头部的switch无法响应点击事件吗？

**Comment by drrino** [comment]
是的  请问这是我哪边写错了嘛

**Comment by oubowu** [comment]
更新到最新的版本试下@Drrino
