### ISSUE TITLE
悬浮的点击事件只有position==0的有效果,其他的就没有

### ISSUE THREAD

**Issue by jyjiawohao** [oubowu/PinnedSectionItemDecoration#44]
mHeaderItemDecoration = new PinnedHeaderItemDecoration.Builder(AdapterFootIndex.TYPE_PARENT)
                .setDividerId(R.drawable.divider).enableDivider(true)
                .setClickIds(R.id.item_ll_title)
                .disableHeaderClick(false)
                .setHeaderClickListener(clickAdapter).create();
        recyclerView.addItemDecoration(mHeaderItemDecoration);
     
 OnHeaderClickAdapter clickAdapter = new OnHeaderClickAdapter() {

        @Override
        public void onHeaderClick(View view, int id, int position) {
            ToastUtil.showToast("tag=="+position);
        }

    };
悬浮的点击事件只有position==0的有效果,其他的就没有

如果在item适配器中自己加点击事件 那么 第一个悬浮没有点击事件 其他的都有

**Comment by oubowu** [comment]
是的 你要同时实现头部点击逻辑和item点击逻辑 这两个是拆开的 头部和其余item实现上本来就不是同一种东西
