### ISSUE TITLE
点击头部时可以将分组闭合吗

### ISSUE THREAD

**Issue by downtail** [oubowu/PinnedSectionItemDecoration#47]
感觉这个不是完全的分组，，

**Comment by oubowu** [comment]
不能啊 这是粘性头部 不是分组

**Comment by downtail** [comment]
伤感，分组和粘性不能同时实现。。。囧。。。

**Comment by downtail** [comment]
后来发现多布局+列表+pinnedsection可以实现粘性分组(可展开闭合)这个功能

**Comment by downtail** [comment]
https://github.com/downtail/ItemDecorationPlus

嗯，自己写了这个功能。
