### ISSUE TITLE
你好，结合第三方下拉刷新，最上面的header无法显示

### ISSUE THREAD

**Issue by gaoyl87** [oubowu/PinnedSectionItemDecoration#5]
结合了https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh库后，顶部的header无法显示，下拉时才显示出来，松手后又不显示，是否是第三方库的header距离计算问题？

**Comment by oubowu** [comment]
我去写个demo看看

**Comment by gaoyl87** [comment]
你直接在你StockActivity这个布局的外面套一个
<in.srain.cube.views.ptr.PtrClassicFrameLayout
    android:id="@+id/ptrClassicFrameLayout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:ptr_duration_to_close="200"
    app:ptr_duration_to_close_header="1000"
    app:ptr_keep_header_when_refresh="true"
    app:ptr_pull_to_fresh="false"
    app:ptr_ratio_of_header_height_to_refresh="1.2"
    app:ptr_resistance="1.7"
    tools:showIn="@layout/activity_list">
</in.srain.cube.views.ptr.PtrClassicFrameLayout>
就好了

**Comment by oubowu** [comment]
这个应该不是库的问题，而是PtrFrameLayout和CoordinatorLayout的Behavior问题
你把activity_stock.xml改成这样再看看效果，我试了是没问题的，如果是PtrFrameLayout最外层的话app:layout_behavior是不起作用的。
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#999999"
              android:orientation="vertical"
              android:padding="10dp"
              app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <in.srain.cube.views.ptr.PtrFrameLayout
        android:id="@+id/fragment_ptr_home_ptr_frame"
        xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        cube_ptr:ptr_duration_to_close="200"
        cube_ptr:ptr_duration_to_close_header="1000"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="1.7">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </android.support.v7.widget.RecyclerView>

    </in.srain.cube.views.ptr.PtrFrameLayout>
</LinearLayout>`

` final PtrFrameLayout ptrFrameLayout = (PtrFrameLayout) findViewById(R.id.fragment_ptr_home_ptr_frame);
        StoreHouseHeader header = new StoreHouseHeader(this);
        header.setPadding(0, 20 * 4, 0, 20 * 4);
        header.initWithString("Ultra PTR");

        ptrFrameLayout.setDurationToCloseHeader(1500);
        ptrFrameLayout.setHeaderView(header);
        ptrFrameLayout.addPtrUIHandler(header);
        ptrFrameLayout.setPtrHandler(new PtrHandler() {
            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }

            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                ptrFrameLayout.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        ptrFrameLayout.refreshComplete();
                    }
                }, 1500);
            }
        });`

**Comment by oubowu** [comment]
这个应该不是库的问题，而是PtrFrameLayout和CoordinatorLayout的Behavior问题
你把activity_stock.xml改成这样再看看效果，我试了是没问题的，如果是PtrFrameLayout最外层的话app:layout_behavior是不起作用的。
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#999999"
              android:orientation="vertical"
              android:padding="10dp"
              app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <in.srain.cube.views.ptr.PtrFrameLayout
        android:id="@+id/fragment_ptr_home_ptr_frame"
        xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        cube_ptr:ptr_duration_to_close="200"
        cube_ptr:ptr_duration_to_close_header="1000"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="1.7">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </android.support.v7.widget.RecyclerView>

    </in.srain.cube.views.ptr.PtrFrameLayout>
</LinearLayout>`

代码
` final PtrFrameLayout ptrFrameLayout = (PtrFrameLayout) findViewById(R.id.fragment_ptr_home_ptr_frame);
        StoreHouseHeader header = new StoreHouseHeader(this);
        header.setPadding(0, 20 * 4, 0, 20 * 4);
        header.initWithString("Ultra PTR");

        ptrFrameLayout.setDurationToCloseHeader(1500);
        ptrFrameLayout.setHeaderView(header);
        ptrFrameLayout.addPtrUIHandler(header);
        ptrFrameLayout.setPtrHandler(new PtrHandler() {
            @Override
            public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
                return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
            }

            @Override
            public void onRefreshBegin(PtrFrameLayout frame) {
                ptrFrameLayout.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        ptrFrameLayout.refreshComplete();
                    }
                }, 1500);
            }
        });`

**Comment by oubowu** [comment]
这个应该不是库的问题，而是PtrFrameLayout和CoordinatorLayout的Behavior问题
你把activity_stock.xml改成这样再看看效果，我试了是没问题的，如果是PtrFrameLayout最外层的话app:layout_behavior是不起作用的。

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#999999"
              android:orientation="vertical"
              android:padding="10dp"
              app:layout_behavior="@string/appbar_scrolling_view_behavior">

```
<in.srain.cube.views.ptr.PtrFrameLayout
    android:id="@+id/fragment_ptr_home_ptr_frame"
    xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    cube_ptr:ptr_duration_to_close="200"
    cube_ptr:ptr_duration_to_close_header="1000"
    cube_ptr:ptr_keep_header_when_refresh="true"
    cube_ptr:ptr_pull_to_fresh="false"
    cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
    cube_ptr:ptr_resistance="1.7">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </android.support.v7.widget.RecyclerView>

</in.srain.cube.views.ptr.PtrFrameLayout>
```

</LinearLayout>

代码：
        final PtrFrameLayout ptrFrameLayout = (PtrFrameLayout) findViewById(R.id.fragment_ptr_home_ptr_frame);
        StoreHouseHeader header = new StoreHouseHeader(this);
        header.setPadding(0, 20 \* 4, 0, 20 \* 4);
        header.initWithString("Ultra PTR");

```
    ptrFrameLayout.setDurationToCloseHeader(1500);
    ptrFrameLayout.setHeaderView(header);
    ptrFrameLayout.addPtrUIHandler(header);
    ptrFrameLayout.setPtrHandler(new PtrHandler() {
        @Override
        public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
            return PtrDefaultHandler.checkContentCanBePulledDown(frame, content, header);
        }

        @Override
        public void onRefreshBegin(PtrFrameLayout frame) {
            ptrFrameLayout.postDelayed(new Runnable() {
                @Override
                public void run() {
                    ptrFrameLayout.refreshComplete();
                }
            }, 1500);
        }
    });
```

**Comment by oubowu** [comment]
智障的要换个行才能显示全
<
LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#999999"
              android:orientation="vertical"
              android:padding="10dp"
              app:layout_behavior="@string/appbar_scrolling_view_behavior">

```
<in.srain.cube.views.ptr.PtrFrameLayout
    android:id="@+id/fragment_ptr_home_ptr_frame"
    xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    cube_ptr:ptr_duration_to_close="200"
    cube_ptr:ptr_duration_to_close_header="1000"
    cube_ptr:ptr_keep_header_when_refresh="true"
    cube_ptr:ptr_pull_to_fresh="false"
    cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
    cube_ptr:ptr_resistance="1.7">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </android.support.v7.widget.RecyclerView>

</in.srain.cube.views.ptr.PtrFrameLayout>
```

</LinearLayout>

**Comment by gaoyl87** [comment]
嗯，可以了，谢谢

**Comment by oubowu** [comment]
觉得好用的话star个哦
