### ISSUE TITLE
pinned title 设置margin后显示问题

### ISSUE THREAD

**Issue by iielse** [oubowu/PinnedSectionItemDecoration#50]
![image](https://user-images.githubusercontent.com/7521943/41087932-b039c7ac-6a70-11e8-9b65-379aff3b9383.png)

我在左边留了点 margin
![image](https://user-images.githubusercontent.com/7521943/41087950-c07ed79c-6a70-11e8-8484-24c6a5618c52.png)

这里是透明的。

但是实际效果
![22](https://user-images.githubusercontent.com/7521943/41088078-1fafbe70-6a71-11e8-8058-ddfa5db0b31a.gif)

你看 最左边的数字14.0被遮住了。 应该不会被遮住。
那里应该是透明色，不是白色呀。

```
vRecycler.addItemDecoration(
                PinnedHeaderItemDecoration.Builder(FoodAdapter.TYPE_TITLE)
                        .setDividerId(R.drawable.transparent)
                        .create())
```
我的设置方式如上。

**Comment by oubowu** [comment]
嗯 复现了下 是锁定绘制区域限制了导致后面的item无法绘制 我更新下库 你再看下 是否正常了

**Comment by oubowu** [comment]
okay 更新到1.2.5问题解决了，你也可以看下我最新提交代码看下是由于什么原因导致的 @iielse
