### ISSUE TITLE
allowBackup=true

### ISSUE THREAD

**Issue by blackbbc** [oubowu/PinnedSectionItemDecoration#55]
在library的manifest文件里设置了这个属性，导致项目合并失败，能不能删掉这个属性呀

**Comment by oubowu** [comment]
https://blog.csdn.net/lang523493505/article/details/79359597

<application
        ...
        android:allowBackup="true"
        tools:replace="android:allowBackup"
        >
</application>

强制library覆盖android:allowBackup

你试下

**Comment by blackbbc** [comment]
@oubowu 谢谢
