### ISSUE TITLE
长按点击事件会触发覆盖在粘性头下面的item的长按事件

### ISSUE THREAD

**Issue by Zh-Xin** [oubowu/PinnedSectionItemDecoration#59]
测试单击事件不会被触发而长按事件会触发

**Comment by oubowu** [comment]
怎么出现的 demo这里貌似不会出现

**Comment by Zh-Xin** [comment]
demo里也出现了，我就在你原有demo基础上添加长按事件log打印发现触发顺序是，item的长按事件->再到头部的长按事件

**Comment by oubowu** [comment]
嗯 找到原因了 在GestureListener的onDown方法里没有去做触摸边界的判断，导致onInterceptTouchEvent每次action_donw时都是返回false，没拦截事件，后续动作才做边界判断拦截，所以把事件传递下去了，我这边处理下，在ItemDecoration设置了OnHeaderClickListener的情况下，凡是点击到头部范围统统拦截所有事件即可

**Comment by oubowu** [comment]
拉下最新的代码，问题解决了，你验证下@hai0shen

**Comment by Zh-Xin** [comment]
好的
