### ISSUE TITLE
一模一样的小标签

### ISSUE THREAD

**Issue by FZ985** [oubowu/PinnedSectionItemDecoration#60]
往上华东的时候，会有一个 一模一样的小标签跟着往上滑动，

有没有 类似像趣头条的评论界面那种粘性，（小标签在顶部，不是和第一个item重叠，但是滑动的时候，小标签和列表 又有那种重叠的效果）

**Comment by oubowu** [comment]
很简单啊，把布局改下不就行了
item_data_with_small_pinned_header.xml改为
`FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:background="#70E593"
    android:layout_height="wrap_content">
    

    <ImageView
        android:layout_marginTop="50dp"
        android:id="@+id/iv_animal"
        android:layout_width="match_parent"
        android:layout_height="120dp"
        tools:src="@mipmap/panda0"/>

    <ImageView
        android:id="@+id/iv_small_pinned_header"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:background="#5A5A5A"
        android:padding="8dp"
        android:textColor="#ffffff"
        android:textSize="18dp"
        tools:src="@mipmap/panda0"
        tools:text="熊猫"/>

</FrameLayout`
