### ISSUE TITLE
如何按照日期分组?求教.

### ISSUE THREAD

**Issue by MagicKim** [oubowu/PinnedSectionItemDecoration#62]
比如2018-9-10这个时间有5条数据,2018-9-11有3条数据,然后将时间作为一个header,这样怎么分组?目前服务端是返回一条json.里面有时间戳.因为想用这个控件,还望指导一下.

**Comment by oubowu** [comment]
bean加个参数是类型 你自己排好序 然后人为添加对应的时间戳的bean插入到列表中 根据bean的type就知道是不是头部了

**Comment by MagicKim** [comment]
每条数据都有时间,我先要判断日期是否相等.然后再做header.目前不知道怎么合理判断相同日期的一天作为头部.

**Comment by oubowu** [comment]
先排序 排序完再根据相邻的两个bean的日期是否相等就知道是不是相同日期了 不是的话添加头部类型的bean

**Comment by MagicKim** [comment]
试了很多次，连map都用上了。数据删除的时候，分组混乱了。🤷‍♂️
还是希望您能帮忙写个demo，我去参考一下。
