### ISSUE TITLE
Note: With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 

### ISSUE THREAD

**Issue by ohshi000** [oubowu/PinnedSectionItemDecoration#66]
Note: With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 

You can continue to use the support library. Historical artifacts (those versioned 27 and earlier, and packaged as android.support.*) will remain available on Google Maven. However, all new library development will occur in the AndroidX library. 

We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by oubowu** [comment]
Yep! I already notice that and prepare to support that. Thanks for your suggestion.

**Comment by oubowu** [comment]
Now it's support AndroidX.   '$group:artifact:$version-androidx' is for AndroidX version and  '$group:artifact:$version' is for normal version. I will maintain two version. @johnzheng00

**Comment by ohshi000** [comment]
@oubowu   Thank you!
