### ISSUE TITLE
配合Smart刷新框架或者BaseAdapter自带的上啦加载更多监听，会把粘性头部顶上去

### ISSUE THREAD

**Issue by leo-andr** [oubowu/PinnedSectionItemDecoration#69]

**Comment by oubowu** [comment]
啥意思 没明白 截个图估计能懂

**Comment by chengzhijun0706** [comment]
@lipiao95 你这个问题解决了么，我遇到了同样的问题
![image](https://user-images.githubusercontent.com/13751034/56551138-1b6d9680-65ba-11e9-85eb-ef8fafb183d8.png)

**Comment by androidCoderxiao** [comment]
请问解决了吗 ？

**Comment by leo-andr** [comment]
没有影响 升级依赖库就好了 很久前的问题了

**Comment by MorningGu** [comment]
> 没有影响 升级依赖库就好了 很久前的问题了

请问你是升级的哪个依赖库啊，我这边也遇到这个问题了，目前smartrefresh的库升级到了1.1.2，pinnedsection的库升级到了1.3.2-androidx
