### ISSUE TITLE
标签点击事件触发不了

### ISSUE THREAD

**Issue by panda912** [oubowu/PinnedSectionItemDecoration#7]
RT，只有在下一个标签和上一个标签在一起的时候，点击事件才有效。

**Comment by oubowu** [comment]
什么意思？不是很清楚你的描述，能具体点吗？

**Comment by oubowu** [comment]
@panda912

**Comment by panda912** [comment]
就是SecondActivity，第一个小标签点击没反应，我试过好多次，第一个点击事件是肯定没反应的，其他的小标签，有时候点击会触发，有时候触发不了 @oubowu

**Comment by oubowu** [comment]
原因很简单，`mRecyclerView.addItemDecoration(new SmallPinnedHeaderItemDecoration.Builder(R.id.iv_small_pinned_header, BaseHeaderAdapter.TYPE_HEADER).enableDivider(true)
              .setDividerId(R.drawable.divider).disableHeaderClick(true).setClickIds(R.id.iv_small_pinned_header).setHeaderClickListener(headerClickAdapter).create());`
disableHeaderClick(true)，我把点击头部禁用了啊

**Comment by oubowu** [comment]
我推了下代码，开启了点击，你再看看 @panda912

**Comment by panda912** [comment]
@oubowu 
1.好吧，我没有注意到disableHeaderClick，个人感觉`setHeaderClickListener`和`disableHeaderClick`是不是重复了，关掉点击事件直接`setHeaderClickListener(null)`就好了；
2.我刚才的代码就是disableHeaderClick(true)，但是还是有的小标签可以点击，是什么情况呢？

**Comment by oubowu** [comment]
因为除了头部那个，其余的都是正常的布局的View来的，粘性头部的原理是在头部绘制出跟那些View一样的布局，它的点击事件啥的是我单独处理的，也就是说其余的小标签是在adapter那里处理的，只有顶部粘性头部是itemdecration处理的

**Comment by oubowu** [comment]
disableHeaderClick刚开始我只是想禁掉整个标签的点击事件，不包括里面的子控件，后来想想没必要，名字也有歧义，所以就是把整个标签和其子控件都禁止掉，现在看来确实是重复了 @panda912
