### ISSUE TITLE
吸顶tab切换

### ISSUE THREAD

**Issue by fangzhouguang** [oubowu/PinnedSectionItemDecoration#71]
吸顶view是tab切换控件，点击了可以响应事件但是tab不会切换，大神有木有解决方案呢

**Comment by oubowu** [comment]
这个不行啊 原理是在recyclerview的item间隙处将view绘制出来的 所以不是一个真实的view来的 你要尝试的话 建议试下这个https://github.com/oubowu/StickyItemDecoration 这个另外一种思路实现

**Comment by fangzhouguang** [comment]
感谢兄台指点，终于搞定哦，揪心死了
