### ISSUE TITLE
请问如果数据源只有一个数组的话，如何动态的添加粘性标签并且分组？有什么思路吗谢谢

### ISSUE THREAD

**Issue by Lsy1992** [oubowu/PinnedSectionItemDecoration#8]

**Comment by oubowu** [comment]
举个例子，你这样说我都不知道你所说的json数组是什么意思，返回数据肯定得带有个分类的字段吧，要不然怎么知道属于那个分组的。

**Comment by Lsy1992** [comment]
不好意思叙述的不够详细，下面是这组数据格式：

```
{
    "call_logs": [
        {
            "mobile": "12580",
            "date": "2016-10-20"
        },
        {
            "mobile": "10086",
            "date": "2016-10-20"
        },
        {
            "mobile": "18812345678",
            "date": "2016-10-19"
        }
    ]
}
```

如上所示，该数据为一组通话记录，现在想根据date来设置标签分组，例如：包含2016-10-20日期的为一个标签“今天“”，包含2016-10-19的为一个标签“昨天”；
因为我在Demo中股票那个界面看到是用了3个不同类型的数组实现的，所以想请教下这样的话应当怎么做？感谢

**Comment by oubowu** [comment]
这种只能你拿到数据后，自己判断date值来识别是哪一天的，建议自己加个字段用于分类，如果数据date是打乱的话，还需要把list重新排序，然后适配器数据还要重新包装下list，所以还要在不同日期数据前面位置插入个表示标签的包装数据

**Comment by Lsy1992** [comment]
能给个方法演示一下单个数据源的操作吗？还是不太明白..../(ㄒoㄒ)/~~
就拿股票demo的例子来说如果只是有一个数组怎么才能让数据对应到标签内？ 遍历循环找到有个标签数组相同tag的就添加？

**Comment by oubowu** [comment]
可以，等下我弄完告诉你，这个用RxJava处理是特别方便的 @Lsy1992

**Comment by Lsy1992** [comment]
谢谢老哥

**Comment by Lsy1992** [comment]
老哥弄好了吗？/(ㄒoㄒ)/~~

**Comment by oubowu** [comment]
稍等 在弄另外一个项目的缓存bug

**Comment by oubowu** [comment]
你看下逻辑，首先gson提取bean，然后取bean的list出来，Observable.from将list元素一个一个输出，toSortedList通过date比较日期排好序，map这里用来做头部数据插入list的转换，最后输出的就是包含头部类型空数据的list了，这时候通过元素的itemType和headerName两个自己添加的字段就可以分辨出是哪种类型的布局和该头部的名称@Lsy1992
`        final String json = "{\n" +
                "    \"call_logs\": [\n" +
                "        {\n" +
                "            \"mobile\": \"12580\",\n" +
                "            \"date\": \"2016-10-20\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"mobile\": \"10086\",\n" +
                "            \"date\": \"2016-10-20\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"mobile\": \"18812345678\",\n" +
                "            \"date\": \"2016-10-19\"\n" +
                "        }\n" +
                "    ]\n" +
                "}";
        Gson gson = new Gson();
        final Bean bean = gson.fromJson(json, Bean.class);
        Observable.from(bean.call_logs).toSortedList(new Func2<Bean.CallLogsEntity, Bean.CallLogsEntity, Integer>() {
            @Override
            public Integer call(Bean.CallLogsEntity callLogsEntity, Bean.CallLogsEntity callLogsEntity2) {
                // 将列表按时间排序，按最晚日期这样排下来
                return callLogsEntity2.date.compareTo(callLogsEntity.date);
            }
        }).map(new Func1<List<Bean.CallLogsEntity>, List<Bean.CallLogsEntity>>() {
            @Override
            public List<Bean.CallLogsEntity> call(List<Bean.CallLogsEntity> callLogsEntities) {

```
            // 通过跟今天日期比较，设置Item的标签属性和添加标签类型的数据

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            final String today = sdf.format(new Date());

            int preRes = Integer.MAX_VALUE;

            for (int i = 0; i < callLogsEntities.size(); i++) {
                final Bean.CallLogsEntity entity = callLogsEntities.get(i);
                entity.itemType = 1;
                final int res = entity.date.compareTo(today);
                if (res > 0) {
                    entity.headerName = "明天";
                } else if (res == 0) {
                    entity.headerName = "今天";
                } else {
                    entity.headerName = "昨天";
                }

                if (preRes != res) {
                    // 说明类型变化了，此时插入一个表示头部的看数据
                    callLogsEntities.add(i, new Bean.CallLogsEntity(null, null, 0, entity.headerName));
                    // 插入了个数据，所以需要往前移动一位
                    i++;
                }

                preRes = res;
            }

            return callLogsEntities;
        }
    }).subscribe(new Subscriber<List<Bean.CallLogsEntity>>() {
        @Override
        public void onCompleted() {

        }

        @Override
        public void onError(Throwable e) {

        }

        @Override
        public void onNext(List<Bean.CallLogsEntity> callLogsEntities) {
            for (Bean.CallLogsEntity e : callLogsEntities) {
                KLog.e(e.toString());
            }
        }
    });`
```

**Comment by oubowu** [comment]
忘了贴bean代码了

`public class Bean {

```
public List<CallLogsEntity> call_logs;

public static class CallLogsEntity {
    public String mobile;
    public String date;

    // 布局类型：0是头部;1是Item
    public int itemType;
    public String headerName;

    public CallLogsEntity(String mobile, String date, int itemType, String headerName) {
        this.mobile = mobile;
        this.date = date;
        this.itemType = itemType;
        this.headerName = headerName;
    }

    @Override
    public String toString() {
        return "CallLogsEntity{" +
                "mobile='" + mobile + '\'' +
                ", date='" + date + '\'' +
                ", itemType=" + itemType +
                ", headerName='" + headerName + '\'' +
                '}';
    }
}
```

}`

**Comment by Lsy1992** [comment]
万分感谢老哥百忙之中指点，我好好捋一捋思路

**Comment by Lsy1992** [comment]
唉弄了一晚上都弄不出来。onNext方法打出来的数据是错误的标签数据，老哥你要是有时间可以直接改股价demo吗？我这样参考还能明白点。。。
**`0 = CallLogsEntity{mobile='null', date='null', itemType=0, headerName='2016-10-20'}`**
**`1 = CallLogsEntity{mobile='12580', date='2016-10-20', itemType=1, headerName='2016-10-20'}`**
**`2 = CallLogsEntity{mobile='10086', date='2016-10-20', itemType=1, headerName='2016-10-20'}`**
**`3 = CallLogsEntity{mobile='18812345678', date='2016-10-19', itemType=1, headerName='2016-10-19'}`**
应当是生成2个标签类型才是正确的，因为有两条是不同的日期，都是昨天和前天的，能帮帮我吗？

**Comment by MagicKim** [comment]
@Lsy1992 这个问题最终是怎么解决的.我们的新业务需求和你这个类似.看看你们踩过坑的人怎么做的.
