### ISSUE TITLE
Header not removed

### ISSUE THREAD

**Issue by 7293hq** [oubowu/PinnedSectionItemDecoration#9]
Header not removed if data in adapter exist and then set to empty

![screenshot_20161029-213124](https://cloud.githubusercontent.com/assets/23138660/19830738/1ea79262-9e28-11e6-90ce-1cc3b17e7470.png)

become

![screenshot_20161029-213053](https://cloud.githubusercontent.com/assets/23138660/19830739/1eab440c-9e28-11e6-8831-01fa07870b6c.png)

Snippet code at the end of onCreate() method on MainActivity in example

```
private void removeData() {
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            removeDataAndUpdateAdapter();
        }
    }, 5000);
}

private void removeDataAndUpdateAdapter() {
    runOnUiThread(new Runnable() {
        @Override
        public void run() {
            mAdapter.setNewData(new ArrayList<PinnedHeaderEntity<Integer>>());
            mAdapter.notifyDataSetChanged();
        }
    });
}
```

**Comment by oubowu** [comment]
It's my fault. I haved fix it, pull the new version. Thanks! @7293hq

**Comment by 7293hq** [comment]
Thanks for the quick respond. The last version fix the issue.
